### ISSUE TITLE
executing build-storybook causes an error under windows

### ISSUE THREAD

**Issue by UsulPro** [storybooks/storybook-deployer#11]
I have error here when use it under Windows:
['node ./node_modules/.bin/build-storybook -o ' + OUTPUT_DIR](https://github.com/kadirahq/storybook-deployer/blob/master/bin/storybook_to_ghpages#L27)

So looks it should be just:
`'build-storybook -o ' + OUTPUT_DIR`
because NPM puts a shell script to `./node_modules/.bin` not js file and adds it to `path`.
Al least it works with windows if I change it manually.

But I hope it should works under Linux same? 
(a bit confused why it not causes any error with Linux?)

**Comment by hipstersmoothie** [comment]
pbulished in v2.5.2
