### ISSUE TITLE
Deploy to monorepo subfolders

### ISSUE THREAD

**Issue by michaelryancaputo** [storybooks/storybook-deployer#14]
I have a monorepo containing a number of react components that i've built using storybook (IT'S AWESOME!).

I would like to generate GH Pages for each of them, however storybook-deployer seems to always deploy to the root of the mono repo for GH Pages instead of the currently active folder.

**Comment by UsulPro** [comment]
@michaelryancaputo Thank you for your interest in this project.

I personally didn't use it with monorepo, but I guess it'll be useful feature! 
At this moment `storybook-deployer` creates a temporary folder and removes it after deploing. Does it work wrong? 
Or could you tell me a few words about your workflow with `storybook-deployer` and what is the desired behavior?

**Comment by michaelryancaputo** [comment]
Sure, my mono repo contains a number of components in sub folders. I generally work directly in those folders, but committing the mono repo to git as one project. 

The desired behavior is that the GH Pages would build inside of the working folder, not within the root of the repo. Currently after running `storybook-deployer`, the GH Pages get published to the root of the monorepo. So the changes get overwritten.

**Comment by UsulPro** [comment]
A PR adding this feature would be super welcome! @michaelryancaputo do you have ideas how to solve this?

**Comment by michaelryancaputo** [comment]
I can take a look, but i'm afraid my shell scripting is lacking :(

**Comment by UsulPro** [comment]
@michaelryancaputo 

We could use the package name to build and then deploy storybooks to `your_root` \ `packageJson.name`\ folder and so separate packages. Is that what are you asking for?

But I wonder about some details of your workflow:

- Do you have individual Git settings in your packages?

- Do you want to deploy all packages at once or to do it individually?

**Comment by michaelryancaputo** [comment]
@UsulPro I only really have gitignore files in each folder, I would only want to deploy when I rev the version of the component on NPM. So individually.

**Comment by hipstersmoothie** [comment]
@UsulPro I am gonna try to implement this. if i can use async/await it'll be a little easier. is that okay?

**Comment by hipstersmoothie** [comment]
or i could just use glob
