### ISSUE TITLE
Use folder other than .storybook

### ISSUE THREAD

**Issue by diegohaz** [storybooks/storybook-deployer#21]
Currently, it's not possible to use `storybook-deployer` with config folder other than `.storybook`. It would be nice to have a `-c path/to/storybook` like in `start-storybook`

**Comment by priley86** [comment]
Does this feature not address this issue @diegohaz ?
https://github.com/storybooks/storybook-deployer#custom-build-configuration

We were able to use a `storybook` directory in Patternfly React...Relevant notes here...
https://github.com/patternfly/patternfly-react
https://github.com/patternfly/patternfly-react/pull/8

**Comment by diegohaz** [comment]
Oh, I missed that. Worked like a charm. Thanks. :)
