### ISSUE TITLE
--output .out mandatory?

### ISSUE THREAD

**Issue by joefraley** [storybooks/storybook-deployer#22]
So the README says this:

https://github.com/storybooks/storybook-deployer#custom-build-configuration

> Custom Build Configuration
> If you customize the build configuration with some additional params (like static file directory), then you need to expose another NPM script like this:
> {
>   "scripts": {
>     ...
>     "build-storybook": "build-storybook -s public -o .out",
>     ...
>   }
> }
> Make sure to set the output directory as .out.

does this mean that you cannot use `storybook-deployer `to deploy a custom directory? my build storybook reads:

`"build-storybook": "build-storybook --config-dir config/storybook --out public/",`

in other words, i want to maintain my public/ directory as the source of truth for my compiled storybook artifacts. is it possible to have `storybook-deployer` use this script?

**Comment by KaySackey** [comment]
`build-storybook` if you don't give it any paramaters will output to `storybook-static`, but this repo actually requires that you use ./out as your directory name. At least that's what I get from reading the code.

**Comment by joefraley** [comment]
ok, that makes sense. does that mean that this line of the documentation is out of date, or misleading?

  > Make sure to set the output directory as .out.

**Comment by KaySackey** [comment]
Kind of, even if you use another directory, it'll just override what you set---at least that's the case for me using yarn instead of npm.
