### ISSUE TITLE
Config to allow deploying existing build folders

### ISSUE THREAD

**Issue by travisbloom** [storybooks/storybook-deployer#26]
My team would like to build our storybook assets at a separate step in the CI flow, and the deploy it at the very end. Ideally we should be able to specify an `existing-output-dir` that storybook should read from instead of building its own static assets.

**Comment by hipstersmoothie** [comment]
This seems to have been implemented. Let me know if it doesn't work for you! @travisbloom 

https://github.com/storybooks/storybook-deployer#skip-build-step

**Comment by travisbloom** [comment]
whoops, forgot to close this out. I added that feature :) https://github.com/storybooks/storybook-deployer/commit/77b259e26b284d076e6069679e694d940e439ce6
