### ISSUE TITLE
Hardcoded remote is too inflexible

### ISSUE THREAD

**Issue by rdjpalmer** [storybooks/storybook-deployer#8]
At the moment the tool is hardcoded to look at `remote.origin.url`. This has caused issues where my fork of an organisation's repository is named `origin`—I've now got a page live under my username as opposed updating the organisation's page.

Now I can go and rename my remote, so this isn't the case, but I think it's a fairly common scenario to be in. What would be great is if the remote could be supplied as an argument to the CLI, e.g.,

``` bash
storybook-to-ghpages --remote origin
```

**Comment by arunoda** [comment]
Okay. We would like to a PR for this with keeping origin as the default.

**Comment by UsulPro** [comment]
In my opinion, this would be a very useful option

**Comment by UsulPro** [comment]
closing by #16
